"""Topic graph orchestration service."""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

from sqlalchemy import delete, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from exposureflow_api.common.audit import record_audit
from exposureflow_api.common.errors import not_found
from exposureflow_api.models import (
    CannibalizationCase,
    ExposureTheme,
    GscPerformanceRow,
    InternalLinkSuggestion,
    SerpQuerySnapshot,
    SerpSlot,
    Site,
    TopicCluster,
    TopicNode,
)
from exposureflow_api.topics.cannibalization import (
    detect_gsc_cannibalization,
    detect_semantic_cannibalization,
)
from exposureflow_api.topics.graph_builder import (
    QueryPageRow,
    aggregate_query_stats,
    build_query_graph,
    coverage_score,
    keyword_level,
    pillar_candidate_score,
)
from exposureflow_api.topics.internal_links import suggest_internal_links


async def _load_gsc_rows(db: AsyncSession, workspace_id: UUID, site_id: UUID) -> list[QueryPageRow]:
    result = await db.execute(
        select(
            GscPerformanceRow.query,
            GscPerformanceRow.page,
            func.sum(GscPerformanceRow.impressions).label("impressions"),
            func.sum(GscPerformanceRow.clicks).label("clicks"),
            func.avg(GscPerformanceRow.position).label("position"),
        )
        .where(
            GscPerformanceRow.workspace_id == workspace_id,
            GscPerformanceRow.site_id == site_id,
        )
        .group_by(GscPerformanceRow.query, GscPerformanceRow.page)
    )
    return [
        QueryPageRow(
            query=row.query,
            page=row.page,
            impressions=int(row.impressions or 0),
            clicks=int(row.clicks or 0),
            position=float(row.position or 0),
        )
        for row in result.all()
    ]


async def _load_serp_keyword_urls(
    db: AsyncSession, workspace_id: UUID, site_id: UUID
) -> dict[str, list[str]]:
    snaps = await db.execute(
        select(SerpQuerySnapshot).where(
            SerpQuerySnapshot.workspace_id == workspace_id,
            SerpQuerySnapshot.site_id == site_id,
        )
    )
    out: dict[str, list[str]] = {}
    for snap in snaps.scalars().all():
        slots = await db.execute(
            select(SerpSlot.url).where(
                SerpSlot.snapshot_id == snap.id,
                SerpSlot.slot_type == "organic",
            )
        )
        urls = [u for (u,) in slots.all() if u]
        if urls:
            out[snap.keyword] = urls[:10]
    return out


async def _get_or_create_default_theme(
    db: AsyncSession, workspace_id: UUID, site_id: UUID
) -> ExposureTheme:
    result = await db.execute(
        select(ExposureTheme).where(
            ExposureTheme.workspace_id == workspace_id,
            ExposureTheme.site_id == site_id,
        )
    )
    theme = result.scalar_one_or_none()
    if theme:
        return theme
    theme = ExposureTheme(
        workspace_id=workspace_id,
        site_id=site_id,
        name="Auto-detected themes",
        description="Generated by topic graph rebuild",
    )
    db.add(theme)
    await db.flush()
    return theme


async def rebuild_topic_graph(db: AsyncSession, workspace_id: UUID, site_id: UUID) -> dict[str, int]:
    rows = await _load_gsc_rows(db, workspace_id, site_id)
    if not rows:
        return {"clusters": 0, "nodes": 0}

    serp_urls = await _load_serp_keyword_urls(db, workspace_id, site_id)
    stats = aggregate_query_stats(rows)
    uf = build_query_graph(rows, serp_keyword_urls=serp_urls)
    groups = uf.groups()
    theme = await _get_or_create_default_theme(db, workspace_id, site_id)

    locked_nodes = await db.execute(
        select(TopicNode).where(
            TopicNode.workspace_id == workspace_id,
            TopicNode.site_id == site_id,
            TopicNode.cluster_assignment_locked.is_(True),
        )
    )
    locked_by_keyword = {n.keyword: n for n in locked_nodes.scalars().all()}

    locked_cluster_ids = {n.topic_cluster_id for n in locked_by_keyword.values()}

    clusters_to_delete = []
    existing_clusters = await db.execute(
        select(TopicCluster).where(
            TopicCluster.workspace_id == workspace_id,
            TopicCluster.site_id == site_id,
        )
    )
    for cluster in existing_clusters.scalars().all():
        if cluster.id not in locked_cluster_ids:
            clusters_to_delete.append(cluster.id)

    if clusters_to_delete:
        await db.execute(
            delete(InternalLinkSuggestion).where(
                InternalLinkSuggestion.topic_cluster_id.in_(clusters_to_delete)
            )
        )

    await db.execute(
        delete(TopicNode).where(
            TopicNode.workspace_id == workspace_id,
            TopicNode.site_id == site_id,
            TopicNode.cluster_assignment_locked.is_(False),
        )
    )
    for cluster_id in clusters_to_delete:
        cluster = await db.get(TopicCluster, cluster_id)
        if cluster:
            await db.delete(cluster)
    await db.flush()

    cluster_count = 0
    node_count = 0
    max_imp = max((s.total_impressions for s in stats.values()), default=1)

    for _root, queries in groups.items():
        if not queries:
            continue
        cluster_stats = [stats[q] for q in queries if q in stats]
        if not cluster_stats:
            continue

        pillar = max(
            cluster_stats,
            key=lambda s: pillar_candidate_score(
                s.best_url or "",
                s.best_url_impressions,
                max_imp,
            ),
        )
        covered = sum(1 for s in cluster_stats if s.best_url and s.best_url_impressions > 0)
        cov = coverage_score(covered, len(cluster_stats))
        total_imp = sum(s.total_impressions for s in cluster_stats)

        cluster = TopicCluster(
            workspace_id=workspace_id,
            site_id=site_id,
            exposure_theme_id=theme.id,
            name=f"Cluster: {pillar.query[:60]}",
            pillar_keyword=pillar.query,
            pillar_url=pillar.best_url,
            coverage_score=cov,
            authority_score=round(min(100.0, cov * 0.8 + 20), 2),
            total_impressions=total_imp,
            last_analyzed_at=datetime.now(UTC),
            metadata_json={
                "query_count": len(queries),
                "build_signals": ["gsc_cooccurrence", "serp_overlap", "url_hierarchy", "token_similarity"],
            },
        )
        db.add(cluster)
        await db.flush()
        cluster_count += 1

        for q in queries:
            if q in locked_by_keyword:
                continue
            s = stats.get(q)
            if s is None:
                continue
            status = "covered" if s.best_url and s.best_url_impressions > 0 else "gap"
            existing = await db.execute(
                select(TopicNode).where(
                    TopicNode.workspace_id == workspace_id,
                    TopicNode.site_id == site_id,
                    TopicNode.keyword == q,
                )
            )
            node = existing.scalar_one_or_none()
            if node and node.cluster_assignment_locked:
                continue
            if node is None:
                node = TopicNode(
                    workspace_id=workspace_id,
                    site_id=site_id,
                    topic_cluster_id=cluster.id,
                    keyword=q,
                )
                db.add(node)
            else:
                node.topic_cluster_id = cluster.id
            node.keyword_level = keyword_level(q)
            node.current_best_url = s.best_url
            node.impressions = s.total_impressions
            node.clicks = s.total_clicks
            node.avg_position = s.best_position
            node.status = status
            node.evidence_json = {
                "cluster_build": "auto",
                "url_count": len(s.urls),
            }
            node_count += 1

    await db.flush()
    return {"clusters": cluster_count, "nodes": node_count}


async def run_cannibalization_detection(
    db: AsyncSession, workspace_id: UUID, site_id: UUID
) -> int:
    rows = await _load_gsc_rows(db, workspace_id, site_id)
    findings = detect_gsc_cannibalization(rows) + detect_semantic_cannibalization(rows)
    created = 0
    cannibalized_keywords: set[str] = set()

    for finding in findings:
        cannibalized_keywords.add(finding.keyword)
        paired = finding.evidence.get("paired_query")
        if paired:
            cannibalized_keywords.add(paired)
        existing = await db.execute(
            select(CannibalizationCase).where(
                CannibalizationCase.workspace_id == workspace_id,
                CannibalizationCase.site_id == site_id,
                CannibalizationCase.keyword == finding.keyword,
                CannibalizationCase.status == "open",
            )
        )
        if existing.scalar_one_or_none():
            continue
        db.add(
            CannibalizationCase(
                workspace_id=workspace_id,
                site_id=site_id,
                keyword=finding.keyword,
                recommendation=finding.recommendation,
                competing_urls=finding.competing_urls,
                evidence_json=finding.evidence,
            )
        )
        created += 1

    if cannibalized_keywords:
        nodes = await db.execute(
            select(TopicNode).where(
                TopicNode.workspace_id == workspace_id,
                TopicNode.site_id == site_id,
                TopicNode.keyword.in_(list(cannibalized_keywords)),
            )
        )
        for node in nodes.scalars().all():
            node.status = "cannibalized"
            node.evidence_json = {
                **node.evidence_json,
                "cannibalization": True,
            }

    await db.flush()
    return created


async def generate_internal_links_for_site(
    db: AsyncSession, workspace_id: UUID, site_id: UUID
) -> int:
    site = await db.get(Site, site_id)
    site_domain = site.domain if site else None
    clusters = await db.execute(
        select(TopicCluster).where(
            TopicCluster.workspace_id == workspace_id,
            TopicCluster.site_id == site_id,
        )
    )
    created = 0
    for cluster in clusters.scalars().all():
        if not cluster.pillar_url:
            continue
        nodes = await db.execute(
            select(TopicNode).where(
                TopicNode.workspace_id == workspace_id,
                TopicNode.topic_cluster_id == cluster.id,
                TopicNode.status.in_(["gap", "stale"]),
            )
        )
        gap_nodes = [
            {
                "keyword": n.keyword,
                "current_best_url": n.current_best_url,
                "status": n.status,
            }
            for n in nodes.scalars().all()
        ]
        for suggestion in suggest_internal_links(
            pillar_url=cluster.pillar_url,
            pillar_keyword=cluster.pillar_keyword,
            gap_nodes=gap_nodes,
            site_domain=site_domain,
        ):
            existing = await db.execute(
                select(InternalLinkSuggestion).where(
                    InternalLinkSuggestion.workspace_id == workspace_id,
                    InternalLinkSuggestion.site_id == site_id,
                    InternalLinkSuggestion.source_url == suggestion.source_url,
                    InternalLinkSuggestion.target_url == suggestion.target_url,
                    InternalLinkSuggestion.approval_status == "pending",
                )
            )
            if existing.scalar_one_or_none():
                continue
            db.add(
                InternalLinkSuggestion(
                    workspace_id=workspace_id,
                    site_id=site_id,
                    topic_cluster_id=cluster.id,
                    source_url=suggestion.source_url,
                    target_url=suggestion.target_url,
                    anchor_text=suggestion.anchor_text,
                    anchor_relevance_score=suggestion.anchor_relevance_score,
                    evidence_json=suggestion.evidence,
                )
            )
            created += 1
    await db.flush()
    return created


async def assign_node_cluster(
    db: AsyncSession,
    workspace_id: UUID,
    site_id: UUID,
    node_id: UUID,
    cluster_id: UUID,
    *,
    lock_assignment: bool,
    actor_user_id: UUID | None,
) -> TopicNode:
    node = await db.get(TopicNode, node_id)
    if node is None or node.workspace_id != workspace_id or node.site_id != site_id:
        raise not_found("Topic node")
    cluster = await db.get(TopicCluster, cluster_id)
    if cluster is None or cluster.workspace_id != workspace_id or cluster.site_id != site_id:
        raise not_found("Topic cluster")

    node.topic_cluster_id = cluster_id
    if lock_assignment:
        node.cluster_assignment_locked = True
    node.evidence_json = {
        **node.evidence_json,
        "manual_assignment": True,
        "assigned_at": datetime.now(UTC).isoformat(),
    }
    await record_audit(
        db,
        action="topic_node.assign_cluster",
        target_type="topic_node",
        target_id=str(node_id),
        workspace_id=workspace_id,
        actor_user_id=actor_user_id,
        metadata={"cluster_id": str(cluster_id), "lock_assignment": lock_assignment},
    )
    await db.flush()
    return node


async def approve_internal_link(
    db: AsyncSession,
    workspace_id: UUID,
    suggestion_id: UUID,
    *,
    approved: bool,
    actor_user_id: UUID | None,
) -> InternalLinkSuggestion:
    suggestion = await db.get(InternalLinkSuggestion, suggestion_id)
    if suggestion is None or suggestion.workspace_id != workspace_id:
        raise not_found("Internal link suggestion")
    suggestion.approval_status = "approved" if approved else "rejected"
    await record_audit(
        db,
        action="internal_link.approve" if approved else "internal_link.reject",
        target_type="internal_link_suggestion",
        target_id=str(suggestion_id),
        workspace_id=workspace_id,
        actor_user_id=actor_user_id,
    )
    await db.flush()
    return suggestion
