"""Default plan definitions per development plan §13."""

from __future__ import annotations

PLAN_DEFINITIONS: list[dict] = [
    {
        "plan_code": "starter",
        "name": "Starter",
        "price_monthly_cents": 9900,
        "price_yearly_cents": 99000,
        "limits_json": {
            "workspace_limit": 1,
            "site_limit": 1,
            "user_limit": 3,
            "gsc_rows_per_month": 100_000,
            "serp_snapshots_per_month": 500,
            "ai_probe_runs_per_month": 100,
            "knowledge_sources": 100,
            "knowledge_facts": 5000,
            "content_generation_runs_per_month": 50,
            "claim_verification_runs_per_month": 100,
            "report_exports_per_month": 10,
            "storage_gb": 5,
            "white_label_enabled": False,
            "client_portal_enabled": False,
            "api_access_enabled": False,
        },
    },
    {
        "plan_code": "professional",
        "name": "Professional",
        "price_monthly_cents": 29900,
        "price_yearly_cents": 299000,
        "limits_json": {
            "workspace_limit": 3,
            "site_limit": 5,
            "user_limit": 10,
            "gsc_rows_per_month": 1_000_000,
            "serp_snapshots_per_month": 5000,
            "ai_probe_runs_per_month": 1000,
            "knowledge_sources": 500,
            "knowledge_facts": 50_000,
            "content_generation_runs_per_month": 300,
            "claim_verification_runs_per_month": 500,
            "report_exports_per_month": 50,
            "storage_gb": 25,
            "white_label_enabled": False,
            "client_portal_enabled": True,
            "api_access_enabled": True,
        },
    },
    {
        "plan_code": "agency",
        "name": "Agency",
        "price_monthly_cents": 79900,
        "price_yearly_cents": 799000,
        "limits_json": {
            "workspace_limit": 25,
            "site_limit": 50,
            "user_limit": 50,
            "gsc_rows_per_month": 10_000_000,
            "serp_snapshots_per_month": 50_000,
            "ai_probe_runs_per_month": 10_000,
            "knowledge_sources": 2000,
            "knowledge_facts": 500_000,
            "content_generation_runs_per_month": 2000,
            "claim_verification_runs_per_month": 5000,
            "report_exports_per_month": 200,
            "storage_gb": 100,
            "white_label_enabled": True,
            "client_portal_enabled": True,
            "api_access_enabled": True,
        },
    },
    {
        "plan_code": "enterprise",
        "name": "Enterprise",
        "price_monthly_cents": 99900,
        "price_yearly_cents": 999000,
        "limits_json": {
            "workspace_limit": 9999,
            "site_limit": 9999,
            "user_limit": 9999,
            "gsc_rows_per_month": 999_999_999,
            "serp_snapshots_per_month": 999_999,
            "ai_probe_runs_per_month": 999_999,
            "knowledge_sources": 999_999,
            "knowledge_facts": 9_999_999,
            "content_generation_runs_per_month": 999_999,
            "claim_verification_runs_per_month": 999_999,
            "report_exports_per_month": 999_999,
            "storage_gb": 9999,
            "white_label_enabled": True,
            "client_portal_enabled": True,
            "api_access_enabled": True,
        },
    },
]

METRIC_TO_LIMIT_KEY: dict[str, str] = {
    "content_generation_runs": "content_generation_runs_per_month",
    "claim_verification_runs": "claim_verification_runs_per_month",
    "gsc_rows": "gsc_rows_per_month",
    "serp_snapshots": "serp_snapshots_per_month",
    "ai_probe_runs": "ai_probe_runs_per_month",
    "report_exports": "report_exports_per_month",
    "knowledge_sources": "knowledge_sources",
    "knowledge_embedding": "knowledge_facts",
}
