"""Registered background job types for ExposureFlow."""

JOB_DEFINITIONS: list[dict[str, str | int | bool | None]] = [
    {
        "job_type": "gsc.sync",
        "description": "Incremental Google Search Console sync",
        "default_schedule": "0 2 * * *",
        "enabled": True,
        "max_retries": 3,
    },
    {
        "job_type": "ga4.sync",
        "description": "GA4 page metrics sync",
        "default_schedule": "0 3 * * *",
        "enabled": True,
        "max_retries": 3,
    },
    {
        "job_type": "serp.snapshot",
        "description": "SERP matrix snapshot collection",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "tech_seo.crawl",
        "description": "Technical SEO crawl",
        "default_schedule": "0 4 * * 0",
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "bing.sync",
        "description": "Bing Webmaster Tools incremental sync",
        "default_schedule": "0 5 * * *",
        "enabled": True,
        "max_retries": 3,
    },
    {
        "job_type": "integration.health_check",
        "description": "Integration connectivity health check",
        "default_schedule": "0 6 * * *",
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "topic_graph.rebuild",
        "description": "Rebuild topic coverage graph from GSC and SERP",
        "default_schedule": "0 7 * * 1",
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "decision.candidates.generate",
        "description": "Generate action candidates from open opportunities",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "roadmap.build",
        "description": "Build exposure roadmap from approved decisions",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "content.generate.grounded_draft",
        "description": "Compile grounded content draft from brief and source pack",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "content.publish_gate.check",
        "description": "Run publish safety gate on content generation run",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "wordpress.publish_draft",
        "description": "Publish approved draft to WordPress",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "knowledge.source.ingest",
        "description": "Ingest facts from knowledge source",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "knowledge.fact.embed",
        "description": "Embed approved knowledge facts",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "strategy.cold_start_research",
        "description": "Cold-start keyword pyramid research",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "execution.job.run",
        "description": "Run execution plane adapter job",
        "default_schedule": None,
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "report.monthly.generate",
        "description": "Generate monthly exposure report for client deliverable",
        "default_schedule": "0 8 1 * *",
        "enabled": True,
        "max_retries": 2,
    },
    {
        "job_type": "exposure.aggregate",
        "description": "Exposure core daily aggregation",
        "default_schedule": "0 1 * * *",
        "enabled": True,
        "max_retries": 3,
    },
]
